### ISSUE TITLE
Problem with typing low letters in this template pa.write-word

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#55] opened 2021-06-10 09:40 UTC
![image](https://user-images.githubusercontent.com/66912801/121501782-355fd280-c9e8-11eb-8271-f65e4e780bc8.png)
Hi! When I make cards with low letters (p, y, g, etc) and make size a little bit bigger, as you can see, these letters (on the screenshot letter g in go) become cut.
I'm editing this massage: this problem appears not only here but in other templates and exercises. That's not crucial but it'd be good to correct it.

**Comment by a34alefeliza** [comment] 2021-06-27 14:12
which exercise is having this behaviour?

**Comment by Dashkinru** [comment] 2021-06-27 15:32
Text Box With Cards <https://i-love-english.pikimoni.net/home.html>
С уважением,
Дарья


вс, 27 июн. 2021 г. в 17:13, Alessandro ***@***.***>:

**Comment by a34alefeliza** [comment] 2021-07-09 06:54
I'm not able to reproduce the issue... which collection shall I select?
![image](https://user-images.githubusercontent.com/9462653/125036275-1a3dbc80-e093-11eb-959a-02632e2f360e.png)

**Comment by Dashkinru** [comment] 2021-07-09 07:09
Irregular Verbs 1

пт, 9 июл. 2021 г., 09:54 Alessandro ***@***.***>:

**Comment by a34alefeliza** [comment] 2021-07-18 12:37
ok I think it's fixed now

**Comment by Dashkinru** [comment] 2021-07-19 09:05
Thank you!

вс, 18 июл. 2021 г., 15:38 Alessandro ***@***.***>:

**Comment by Dashkinru** [comment] 2021-07-19 11:44
I've checked the exercise now and still see the problem. Look at "go". [image:
image.png]

And the space between lines have become quite small. Some letters are
intersecting now. [image: image.png]
С уважением,
Дарья


пн, 19 июл. 2021 г. в 12:04, English Teaching ***@***.***>:

**Comment by a34alefeliza** [comment] 2021-07-27 12:15
I don't see the images you attached....
BTW did you try playing with size/size2/text?
_size_: allows you to change box's width
_size2_: allows you to change box's height
_text_: allow you to change text size

**Comment by Dashkinru** [comment] 2021-08-07 19:28
ok. There was my mistake as well. I got it. But a small problem still exists in "add card" option.
![image](https://user-images.githubusercontent.com/66912801/128611782-65e3e4a6-45d7-43e4-b352-450854b67897.png)
If the word is very small "low letters" are ok, but if it's a bit bigger, the lower part is not visible. 
Exercise Text Box With Cards, Collection Verbs Pictures (Type 3 Forms).

**Comment by a34alefeliza** [comment] 2021-08-09 08:47
Ok understood, this is a card. I thought it was a text... fixed.

**Comment by Dashkinru** [comment] 2021-08-09 10:51
Thanks!

пн, 9 авг. 2021 г., 11:47 Alessandro ***@***.***>:

**Closed as completed** 2021-08-11 13:47 UTC
Labels: enhancement
