### ISSUE TITLE
A new bug in hw

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#72] opened 2022-08-10 06:19 UTC
In this template /pa.office/ the image's size changes drestically when the ex is on my screen and when it is later on the student's sreen. Have a look pls. I'm sending you two comparisons: with images and with text (where the size difference is not only clear visible but also doesn't let do the ex)

MY PAGE
![image](https://user-images.githubusercontent.com/66912801/183827126-3f89d5f5-91dd-4409-8eb4-874e853f7978.png)

STUDENT'S PAGE
![image](https://user-images.githubusercontent.com/66912801/183828465-15def3dd-5b75-49cd-b013-9d2722e173c9.png)

MY PAGE
![image](https://user-images.githubusercontent.com/66912801/183829226-968d8f28-21f8-486d-ac35-3b9bf3c52c80.png)

STUDENT'S PAGE
![image](https://user-images.githubusercontent.com/66912801/183829294-cd431d64-fee3-47f5-87db-60b61fd2b22d.png)

**UPD** (in case you've already seen the message)

In I Can Speak ex On the Table (can't find the template's name) the difference in size is very large too. Images 2 are huge. 
On my sreen
![image](https://user-images.githubusercontent.com/66912801/184348486-97cd93d5-6168-4b0a-997b-68f4cf1b90e1.png)

Student's page
![image](https://user-images.githubusercontent.com/66912801/184348358-f926101f-8a9f-4392-ac57-4d741832b76b.png)

**Comment by a34alefeliza** [comment] 2022-09-14 10:32
I am not able to reproduce the issue... I've added I Can Speak > On the table to my workplan, and from workplan to homework. If I connect as a student and open homework everything is good:

TEACHER
<img width="957" alt="image" src="https://user-images.githubusercontent.com/9462653/190131324-8cb799c2-08a8-46e8-bc1f-e27ed5965c7e.png">

STUDENT
<img width="959" alt="image" src="https://user-images.githubusercontent.com/9462653/190131344-a26217bd-3bc9-43bf-a64e-e50c9bee1a58.png">

Can you check again? Maybe this issue is already solved?

**Comment by Dashkinru** [comment] 2022-10-21 11:09
Hi! It dawned on me why on your screenshot above everything is OK with the size on the student's page. The student was still connected to the classroom because you share the same background. Now try to do the same but first disconnect the student so that their background becomes white.

**Comment by a34alefeliza** [comment] 2022-10-21 15:36
WOW! I just want to congratulate with you for spotting that. It saved me a lot of time... true, if I disconnect the student from the classroom I can reproduce the issue. It will be fixed soon. Well done!

**Comment by Dashkinru** [comment] 2022-10-21 16:04
))))))

пт, 21 окт. 2022 г., 18:37 Alessandro ***@***.***>:

**Comment by a34alefeliza** [comment] 2022-10-29 08:10
that problem is now fixed. I am still struggling with text alignment, but hopefully this is not blocking you with homework...
Let me know if there is anything else to fix on homework. I understood from Yulia that you are going to publish a post about it.

**Comment by Dashkinru** [comment] 2022-10-29 09:34
Hi. Ok. Yeah, next week I'm planning to go through the homework section one more time and post about this feature.
There some minor typos I saw but don't remember where. I'll tell you about them in a few days.

A question.
The function "archive" make the task be deleted completely or there's a way for a teacher to bring it back if necessary?

**Comment by a34alefeliza** [comment] 2022-11-25 17:32
once archived, tasks are just not visible but they do exist on database. In case they are needed, is it possible ti implement a functionality to unarchive them.

**Closed as completed** 2023-01-19 10:27 UTC
Labels: bug
